#!/bin/bash
set -euo pipefail

source "$(dirname "$0")/_common"
export PATH="$env/bin:$PATH"

kernel="$(uname -s)"
machine="$(uname -m)"

case "$kernel/$machine" in
    Linux/x86_64)
        echo "linux-64";;

    Darwin/x86_64)
        echo "osx-64";;

    Darwin/arm64)
        echo "osx-64";;

    *)
        echo "unsupported kernel/machine: $kernel/$machine" >&2
        exit 1;;
esac
