#!/bin/bash
set -euo pipefail

source "$(dirname "$0")/_common"
export PATH="$env/bin:$PATH"

CONDA_SUBDIR="${CONDA_SUBDIR:-$("$repo"/devel/conda-subdir)}"
export CONDA_SUBDIR

wget "$(
    curl -fsSL https://api.anaconda.org/release/nextstrain/nextstrain-base/latest | jq -r '
          .distributions
        | map(select(.attrs.subdir == env.CONDA_SUBDIR))
        | .[0].download_url
        | if startswith("//") then "https:\(.)" else . end
    '
)"
