package:
  name: nextstrain-base
  version: "{{ environ['VERSION'] }}"

build:
  number: 0
  pin_depends: strict

source:
  path: .

about:
  home: https://nextstrain.org
  doc_url: https://docs.nextstrain.org/
  dev_url: https://github.com/nextstrain/conda-base
  summary: Base Nextstrain runtime (meta-package)
  description: >
    This meta-package depends on all the other packages needed for a base
    Nextstrain runtime installed as a Conda environment.  As the
    nextstrain/base image is to Nextstrain CLI's Docker runtime, this
    nextstrain-base package is to Nextstrain CLI's Conda runtime.
  license: >
    The license for this meta-package is MIT; individual tools vary.

requirements:
  run:
    #
    # First-party
    #
    # XXX TODO: Include fauna?
    #
    - augur
    - auspice
    # Pin minimum version for correct dependency resolution
    # otherwise evofr will get downgraded to v0.1.18 build 0
    - evofr >=0.1.19
    - nextalign
    - nextclade2
    - nextclade
    - nextstrain-cli
    - pathogen-embed

    #
    # Third-party
    #
    # XXX TODO: Pin some of these to the same versions the Docker runtime uses?
    # XXX TODO: No package available for Python envdir package.
    # XXX TODO: No package available for less.
    # XXX TODO: Omits pysam… but it may be unnecessary in the Docker runtime?
    # XXX TODO: Omits pango-designation… but it may be unnecessary in the Docker runtime?
    #
    # Include bash so that a newer version is guaranteed to be available on
    # systems with an older bash.  This is similar to how our Docker runtime
    # image includes its own bash too.
    #
    - awscli >=2
    - bash
    - bio >=1.8.0
    - bzip2
    - csvtk
    - coreutils
    - curl
    - epiweeks
    - git
    - gawk
    - grep
    - gzip
    - iqtree >=3
    - jq
    - ncbi-datasets-cli
    - openpyxl
    - pango_aliasor
    - perl
    - pyarrow
    - ruby
    - sed
    - seqkit
    - snakemake >=9.0.0,<10
    - snakemake-storage-plugin-http
    - snakemake-storage-plugin-s3
    - sqlite
    - tar
    - tsv-utils
    - unzip
    - wget
    - xlrd
    - xz
    - zip
    - zstd
